/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "shifter_switches.h"
#include "shifter_switches_aliases.h"
#include "shifter_isr.h"
#include "pwm_clock.h"
#include "PWM.h"
#include "en_1_2.h"
#include "en_1_2_aliases.h"
#include "en_3_4.h"
#include "en_3_4_aliases.h"
#include "front_motor.h"
#include "rear_motor.h"
#include "in_1.h"
#include "in_1_aliases.h"
#include "in_2.h"
#include "in_2_aliases.h"
#include "in_3.h"
#include "in_3_aliases.h"
#include "in_4.h"
#include "in_4_aliases.h"
#include "quad_dec_clk.h"
#include "decoder_A.h"
#include "decoder_A_aliases.h"
#include "decoder_B.h"
#include "decoder_B_aliases.h"
#include "QuadDec.h"
#include "rear_pot_feedback.h"
#include "rear_pot_feedback_aliases.h"
#include "ADC_SAR_SEQ.h"
#include "I2C.h"
#include "I2C_I2C.h"
#include "I2C_PINS.h"
#include "I2C_I2C_PVT.h"
#include "I2C_PVT.h"
#include "I2C_BOOT.h"
#include "timer_isr.h"
#include "timer_clock.h"
#include "Timer.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "ADC_SAR_SEQ_IRQ.h"
#include "ADC_SAR_SEQ_intClock.h"
#include "I2C_SCBCLK.h"
#include "I2C_sda.h"
#include "I2C_sda_aliases.h"
#include "I2C_scl.h"
#include "I2C_scl_aliases.h"
#include "I2C_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

